
server:
  port: 8761
  
spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: oracle
    password: sarasu10
    driver-class-name: oracle.jdbc.OracleDriver
     
    

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
   
   