
server:
  port: 9001

spring:
  application:
      name: ORDER-SERVICE
    
#  datasource:
#    url: jdbc:oracle:thin:@//localhost:1521/orcl
#    username: oracle
#    password: sarasu10
#    driver-class-name: oracle.jdbc.OracleDriver
    
    
    
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

   